### ISSUE TITLE
Question about PyramidGrid 

### ISSUE THREAD

**Issue by LoveMiki** [LouieYang/MCL#3]
Dear author, thanks for sharing the codes.

In the paper, you mentioned that the PyramidGrid first crops the image evenly into an H × W grid before sending to the encoder. That is, for example, if the input size of an image is 84x84 and evenly cropped into 2x2 patches. The patches are resized to the same size as the input (i.e., 84x84) and stacked together before sending to the encoder. Is that right?
However, I do not see any crop operation in function forward_Grid. Can you explain how did you implement PyramidGrid?

**Comment by LouieYang** [comment]
The crop, resize&stack is implemented in [grid_datasets.py](https://github.com/LouieYang/MCL/blob/master/dataloader/grid_datasets.py). Specifically, we stack grid patches of a single image in the channel dimension such that the input image tensor is of shape [#grids x 3, H, W] instead of [3,  H, W]. 

In forward_Grid function, we reshape the input to [batch_size x #grids, 3, H, W] to get feature map output and use average pooling to encode each grid cell to a single feature vector.

**Comment by LoveMiki** [comment]
> The crop, resize&stack is implemented in [grid_datasets.py](https://github.com/LouieYang/MCL/blob/master/dataloader/grid_datasets.py). Specifically, we stack grid patches of a single image in the channel dimension such that the input image tensor is of shape [#grids x 3, H, W] instead of [3, H, W].
> 
> In forward_Grid function, we reshape the input to [batch_size x #grids, 3, H, W] to get feature map output and use average pooling to encode each grid cell to a single feature vector.

Thank you for your quick response. I have another question.
In Table 1, DN4 achieved 54.66 and 71.26 in the 5-way 1/5-shot setting using VanillaFCN, while the original paper only achieved 51.24 in the 5-way 1-shot setting. There is a big performance gap in 1-shot setting but it is almost the same in the 5-shot setting. What is the underlying reason for this phenomenon?
Thanks.

**Comment by LouieYang** [comment]
There are mainly two reasons we suppose:
1. We use the original image instead of the pre-cropped image such that data augmentation like Resize(92), RandomCrop(84) is used in our implementation.
2. We use more episodes (iterations) per epoch in our implementation.
