### ISSUE TITLE
Is DeepEMD really a unidirectional method?

### ISSUE THREAD

**Issue by Frankluox** [LouieYang/MCL#4]
Thanks for bringing in a new perspective with a bidirectional walk method! But I have a question and hope the authors could clarify. In DeepEMD, every query feature is very likely to be assigned to multiple support features (weights of features are different; also, the optimization process does not restrict a strict matching), so the formula in figure 1(b) may not be correct. In fact, the calculation of EMD distance treats query features and support features equally, and it tries its best to find an optimal assignment depending on all support and query features. Thus assignment cannot be made based on a single query feature, in contradiction with the formula in figure 1(b). In addition, I can imagine a bidirectional optimization process (somewhat like Coordinate Ascent)of DeepEMD that in each iteration updates the connection by looking at only query or support features. DeepEMD should therefore be considered as a bidirectional method. If I am correct, DeepEMD has nearly all the benefits that MCL can offer. For example, higher emphasis is given to support(query) features that have a large average similarity to query(support) features (the weight in DeepEMD; the expected visit in random walk of MCL); higher emphasis is given to similar pairs (low cost in DeepEMD; the high probability of revisiting similar pairs in MCL).  If I am again correct (maybe I miss something), I will be curious about the real motivation and benefit of MCL.

**Comment by LouieYang** [comment]
Yes, it would be proper to say strict EMD (strict matching) is a unidirectional paradigm instead of DeepEMD in figure 1(b). 

The motivation of MCL is quite simple: we want the ground truth owns as many closely related local pairs (within a large support features pool) as possible and want to make a joint classification according to this. We seek accessibility (somewhat reflecting skip relation instead of the directed ones) and find it inherently a valid distribution for classification. 

I think we have pointed out the difference between MCL and DeepEMD on Page 6 (Sec.4.1, where we also say strictly, their cross-reference encodes the bidirectional information as you mentioned). To compare, DeepEMD focuses on assigning higher emphasis to similar pairs since the weight in DeepEMD is actually the weight on edges in the bipartite graph. Instead, MCL focuses on assigning higher emphasis to query (support) features (the nodes in the bipartite graph) where \pi(q) actually reflects the task-centrality on query features and \pi(S) reflects the task-centrality on support features.

**Comment by Frankluox** [comment]
Got it. Thank you so much!
